### PR TITLE
Add osx-arm64 build.

### PR DESCRIPTION
**Pull request by erykoff**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by erykoff** [comment]
@conda-forge-admin, please restart ci

**Comment by erykoff** [comment]
@conda-forge/aggdraw This is ready.

**Comment by djhoese** [comment]
Looks good, but why isn't this done by a bot?

**Comment by djhoese** [comment]
This suggests there are few more dependencies to add to meta.yaml: https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock

Is that blog out of date?

**Comment by erykoff** [comment]
To answer your first question, I did this myself rather than asking the bot because I've done it enough that I can just do it by hand rather than registering it with the bot.
To answer your second question, you only need the cython, numpy, and pybind11 cross-dependencies if the project depends on them.  For `aggdraw`, we only need `python` and `cross-python`.

**Pull request merged**
